#Vaadin Copilot Integration Runtime Properties
#Tue Jul 28 12:03:17 ART 2026
endpoint=http\://127.0.0.1\:56632/vaadin/copilot-e2a26822-4451-492a-b12a-cc2b7dbc2666
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
